### ISSUE TITLE
Build package with linux kernel extra modules?

### ISSUE THREAD

**Issue by 3v1n0** [zabbly/linux#27]
Various modules included in the ubuntu's `linux-modules-extra-*` packages aren't included in zabbly, would be possible to add an extra package with them?

As per things such as binder_linux

**Comment by stgraber** [comment]
We build with a config generally matching Ubuntu's with occasional re-syncs.

For this particular example (binder), the reason we don't have it is because binder cannot be built as a module in the mainline kernel, this is an Ubuntu-specific kernel change which allows it.

https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/oracular/commit/drivers/android/Makefile?id=dd465b2175fa41de7dc12cd98a08feff6311064a

As we don't carry out-of-tree patches in this kernel build, binder will remain disabled until the mainline kernel supports building it as a module.
