### ISSUE TITLE
Would it be possible to enable netkit?

### ISSUE THREAD

**Issue by graveland** [zabbly/linux#29]
Specifically: CONFIG_NETKIT=m

This is for testing cilium and netkit in kubernetes. I checked 6.11.7-zabbly+ and it's not enabled there at least.

**Comment by stgraber** [comment]
You're in luck, I was just doing some config tweaks. That one most likely didn't get picked up initially because the default decision is to go for modules for anything, then if not possible as a module go with the default, which for NETKIT is disabled.

I've pushed an updated config now. I'm still waiting for this week's bugfix release to come out but Greg tags it, it'll be rolled out with netkit enabled.

**Comment by graveland** [comment]
Fantastic, thanks!
